# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 659985f027998a3937995f4903ff5831ffea30f427445a61154f59c7f9f1c98871a8bb2bb7c5fed1b81a51dd13e4ca943b379ac42db571701d589d014d001712

test:
  secret_key_base: 94fb0b09d837deadbd807f7ff735dc7bfb93b98e10cc815d74b0777234e605fc836e9bedced82887cc309dd648dd81a0f1262d7f6a6dcca9a454e79cd48dd4ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
